# Generated by Django 4.1.7 on 2023-02-17 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends_lessons', '0004_user_friends'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
